### ISSUE TITLE
Uncaught TypeError: editor.getScreenLineCount is not a function

### ISSUE THREAD

**Issue by doggan** [efatsi/block-travel#22] opened 2017-06-05 19:18 UTC
[Enter steps to reproduce:]

1. Open the Atom Settings panel.
2. Place your cursor in one of the text input fields in the Settings UI (for example, Core -> Ignored Names).
3. Press `alt-down` to trigger block travel.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [block-travel](https://github.com/leejarvis/block-travel) package 1.0.5

### Stack Trace

Uncaught TypeError: editor.getScreenLineCount is not a function

```
At /Users/shyam/.atom/packages/block-travel/lib/block-travel.coffee:4

TypeError: editor.getScreenLineCount is not a function
    at blockTravel (/packages/block-travel/lib/block-travel.coffee:4:22)
    at /packages/block-travel/lib/block-travel.coffee:52:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -1:25.4.0 core:cancel (input.hidden-input)
     -1:24.7.0 project-find:show (input.hidden-input)
     -1:24.5.0 core:paste (input.hidden-input)
     -1:24.4.0 core:confirm (input.hidden-input)
  2x -1:15.5.0 core:cancel (div.results-view.focusable-panel)
  2x -1:07.6.0 pane:show-next-item (div.results-view.focusable-panel)
  2x -1:05.6.0 core:close (input.hidden-input)
     -1:02.4.0 core:cancel (div.results-view.focusable-panel)
     -1:01.9.0 core:close (div.results-view.focusable-panel)
     -0:50.7.0 project-find:show (input.hidden-input)
     -0:42 editor:consolidate-selections (input.hidden-input)
     -0:42 core:cancel (input.hidden-input)
  2x -0:12.5.0 editor:move-to-end-of-word (input.hidden-input)
     -0:12.1.0 block-travel:move-down (input.hidden-input)
 15x -0:06.4.0 editor:move-to-end-of-word (input.hidden-input)
     -0:02.7.0 block-travel:move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
autocomplete-paths 1.0.5 
block-travel 1.0.5 
busy-signal 1.4.3 
docblockr 0.10.3 
editorconfig 2.2.2 
file-icons 2.1.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-hdl 0.1.5 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
monokai 0.24.0 
pretty-json 1.6.3 
project-manager 3.3.5 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
theme-switcher 1.1.0 
unity-shader-files 0.3.1 
```

**Comment by efatsi** [comment] 2017-06-05 22:19
Triggering block travel within a single line text field is a bit of a weird use case for this. I'm unable to reproduce in a regular text editor. Also this package is now defunct ... so closing this issue out.

**Closed by efatsi** 2017-06-05 22:19 UTC
